# Generated by Django 5.0.3 on 2024-04-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("destination", models.TextField()),
                ("passenger", models.TextField()),
                ("bags", models.PositiveIntegerField(default=0, null=True)),
                ("first_class", models.BooleanField(default=False)),
            ],
        ),
    ]
